name: Doc

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: sudo apt-get install doxygen

    - name: Build C++ documentation
      working-directory: ${{github.workspace}}/doc
      shell: bash
      run: doxygen dox.conf

    - name: Upload as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ${{github.workspace}}/doc/html
